### ISSUE TITLE
callback for state machine events

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#204]
Shaz: In P, it is possible for the programmer to supply a logger function.  When an “interesting” thing happens in the runtime, such as event enqueue/dequeue, state transition, push/pop, etc., the logger is called with an enum code for the interesting thing that happened together with other data relevant to that interesting thing.  Is something like this already available in the P# runtime?  The Batch team is requesting this feature to collect custom statistics about the work happening in the pool server.

**Comment by akashlal** [comment]
The Logger in P# has the following interface:
https://github.com/p-org/PSharp/blob/master/Source/Core/IO/Logging/ILogger.cs

As you can see, it is very text based. Can you point us to the P logger and/or what kind of interface would they rather want?

**Comment by shazqadeer** [comment]
https://github.com/p-org/P/blob/master/Src/Prt/API/Prt.h

Take a look at the file above, in particular, at the PRT_LOG_FUN function type and the PRT_STEP enum type.

**Comment by shazqadeer** [comment]
One possible approach is to provide a base class such as following:

class StateMachineLogger {
    public virtual void OnCreate(MachineId createdMachine) { }

    public virtual void OnEnqueue(MachineId source, Event e, MachineId target) { }

    ...
}

The P# programmer can extend this base class and override appropriate handlers.  When the P# runtime is initialized, an instance of this class is passed.  The P# runtime guarantees to call the correct handler when a relevant action occurs.  One disadvantage of this approach is that the overhead of a method call is paid even if a particular method is not overridden.

**Comment by akashlal** [comment]
@pdeligia What do you think of this? Shaz is proposing a more structured logger than having a simple Enum that details the current activity. This might be good to have. We can provide a default implementation where all methods like `OnEnqueue` get lowered to the simple string logger.

**Comment by shazqadeer** [comment]
I just want to point out that the main utility of this new logging feature is not more structured logging but rather that the invocations of the logging methods are being done from within the P# runtime based on important things happening there.  Of course, more structured logging is also a feature.

**Comment by akashlal** [comment]
But what would you like to do besides creating a (custom) log of what happen in the execution?

**Comment by pdeligia** [comment]
We already do these default logging invocations from the P# runtime (printing e.g. `<SendLog> ... sends event to ...`), so we mainly want to expose this functionality to the user so that they can override it and change the default message to a custom one?

I think what Shaz proposed above is great (and we could even pass `enum` inside to make it a bit more structured). I don't think the overhead of the extra call matters much, we can just use the attribute `[MethodImpl(MethodImplOptions.AggressiveInlining)]` which hints to inline the method if possible.

All these methods could be part of the existing `ILogger` interface that we have. One problem with that though is that the user will need to provide an implementation for each method which can be tiring (at least for now -- there are apparently plans from C# team to provide default member implementations in interfaces in the future). However, we could expose our default logger as public, so that the user can just override the methods they require there (this would be what Shaz proposed as `StateMachineLogger`).

**Comment by shazqadeer** [comment]
James Wei in the Batch team wanted this functionality.  I believe the intention was to calculate various metrics about the execution for performance/profiling reasons.

**Comment by pdeligia** [comment]
Logging was improved with runtime callbacks in #229 by @TedHartMS.
