### ISSUE TITLE
Sharing annotations across multiple states

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#216]
Nar: I have a lot of statements like this in many states in the pool machine. In a typical coding pattern, these would be encapsulated in a common construct. However its hard to do here. For example, if there is one more event that I need to push, I need to add it all the states in the pool machine.  Are there ideas of improving the language constructs?

**Comment by akashlal** [comment]
@pdeligia 
Can `MachineStates` currently be inherited from others?

**Comment by pdeligia** [comment]
Nope, but I just opened a pull request (#218) for this  :-) Have a look and let me know what you think (feel free to tweak directly on that branch of course).

Also added lots of new related unit tests.

**Comment by akashlal** [comment]
Thanks, this looks great! I will check with Nar if this helps him (but he will want the language syntax for it).

**Comment by pdeligia** [comment]
I think this will work out of the box, as long as we provide syntax for declaring state inheritance so that it can be properly translated.

By default `state Foo` would be translated to `class Foo : MachineState`. If we added something like `state Foo inherits Bar` (`inherits` is a new keyword, maybe you have a better suggestion?), translated to `class Foo : Bar`, and also added a compiler check that `Bar` is inheriting a `MachineState` (or maybe we leave this to be checked dynamically, because someone might be inheriting from a state that is in a base machine in some other dll, probably making this analysis more complicated), maybe it would work?

**Comment by akashlal** [comment]
Assigned to @TedHartMS to add support in `.psharp` syntax.

**Comment by pdeligia** [comment]
Done in #218.
