### ISSUE TITLE
scheduling points reporting is broken

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#225]
Running this command:
```
PSharpTester.exe /test:bin\Debug\ProcessScheduler.exe /i:1000 /max-steps:50  /explore
```
On `PSharpLab\Samples\LivenessRegression\ProcessScheduler` returns something like the following:
```
..... Number of scheduling points in fair terminating schedules: 210 (min), 1 (avg), 465 (max).
```
And that too only when a bug is found. Otherwise the line is skipped.

**Comment by pdeligia** [comment]
@akashlal this bug (well its two bugs) only appears when using `/explore`, right?

**Comment by akashlal** [comment]
It happens even when not using `/explore`. This command: 

'PSharpTester.exe /test:bin\Debug\ProcessScheduler.exe /i:100 /max-steps:50' 

returns (note the avg):

`..... Number of scheduling points in fair terminating schedules: 435 (min), 87 (avg), 435 (max).`

**Comment by pdeligia** [comment]
This is now fixed.

@akashlal this was the culprit: https://github.com/p-org/PSharp/commit/6c99be72a4780f1f5c61d4e63ffdf43819315cc6

We only incremented `TotalExploredFairSteps` if `HasReachedMaxSchedulingSteps` is not true. If `TotalExploredFairSteps == 0` then the above is not printed (and I think also messes up with the statistics). I now changed it so that this statistic is always taken into account.

This is quite old code (>6 months). I am not very sure why we had added this conditional! And many benchmarks will not exhibit the bug, so it was quite easy to miss.

Can you confirm, and close this issue?

**Comment by akashlal** [comment]
Confirmed. Its working fine now.
