### ISSUE TITLE
Support for DPOR

### ISSUE THREAD

**Issue by ankushdesai** [p-org/PSharp#232]
Does P# support DPOR now?
Can you please point me to how I can use it?

**Comment by pdeligia** [comment]
Hi Ankush, to enable it you need to pass the `/sch:dpor` (DPOR) or `/sch:rdpor` (randomized-DPOR) when invoking the `PSharpTester.exe` tool.

I think using randomized-DPOR is better, as we found it to perform much better than the purely DFS-based one. Sadly we did not have much time to seriously evaluate these strategies yet (because we run out of time as Paul's internship was finishing), but we think they will be very useful (at least as part of a portfolio of strategies). Any feedback is highly appreciated!

Perhaps @paulthomson can advise more regarding this feature (but I think he is on holidays right now!).

**Comment by ankushdesai** [comment]
Thanks Pantazis, few more questions.

What is the difference between randomized-dpor and dpor?

Can you please point me to a P# sample where DPOR based search finishes exploring all the executions.
I would like to play around with that sample and would like to then see how DPOR performs for some of the P to P# samples.

**Comment by pdeligia** [comment]
I think the main difference between randomized and non-randomized DPOR, is that the randomized DPOR will randomly choose to reverse some races while exploring a program in a DFS manner. Due to the extra bit of randomness, this could lead the scheduler to explore potentially more interesting schedules, whereas the DFS-DPOR might only explore a specific part of the schedule-space or get stack in a loop and not be able to escape (similar to a regular DFS scheduler).

I am not sure if we have a specific sample (besides very trivial programs) were DPOR managed to finish exploring all executions. @paulthomson do you have any sample to suggest?
