### ISSUE TITLE
VS unable to find unit tests

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#233]
I can no longer run unit tests from VS. It is unable to discover any tests.

**Comment by pdeligia** [comment]
Strange. I confirm that I have the same issue. The nuget package `xunit.runner.visualstudio` v2.2.0 is responsible for running xUnit tests from VS. I am not sure what happened, since our test projects reference it (and we did not change it, so I can't see how we could have broken it). Perhaps we need to check if there is a newer version (maybe a VS update broke it).

**Comment by pdeligia** [comment]
Meanwhile, tests can be run via command line as a workaround:
```
powershell -c .\Tests\run-unit-tests.ps1
powershell -c .\Tests\run-integration-tests.ps1
```

**Comment by akashlal** [comment]
It works now. Not sure what had happened. Closing for now.
