### ISSUE TITLE
question about deadlock reporting

### ISSUE THREAD

**Issue by shazqadeer** [p-org/PSharp#392]
We are building a compiler from P to P#.  We have a sample program in which there are two machines and an execution in which the first machine terminates and the second machine blocks at a receive.  PSharpTester reports a deadlock.  Is that expected?  What is the specification for when PSharpTester reports a deadlock?

**Comment by pdeligia** [comment]
Yes, based on your description this is expected. The P# tester terminates a testing iteration when the serialized execution of a P# program reaches quiescence, i.e. no more machines can be scheduled for the following (combination of) reasons:
- machines have not halted but their queue is empty
- machines have halted
- machine are waiting to receive an event

If the P# program reaches quiescence and there is one or more machines waiting to receive an event, then a deadlock is reported. This means that the tester found a buggy execution where the P# program could not make progress as expected.

Btw, if I remember correctly, the above only applies for finite executions, i.e. if the execution terminates because of max steps limit is reached then we do not report a deadlock, since we cannot be sure if the machine would eventually receive the event its waiting for. But I need to double check this.

**Comment by shazqadeer** [comment]
I am still puzzled.  By "waiting to receive an event", do you mean waiting at an explicit receive statement?  So, if one or more machines were waiting to receive an event in a state, it would not qualify as a deadlock?

**Comment by pdeligia** [comment]
Yes, when I said "waiting to receive an event" above, I meant waiting at an explicit receive statement. Regular (implicit) event receives in a state do not qualify for a deadlock.

**Comment by pdeligia** [comment]
Closing this issue, feel free to reopen @shazqadeer if you want to discuss this more!
