### ISSUE TITLE
Assert and Assume annotations on Events

### ISSUE THREAD

**Issue by ankushdesai** [p-org/PSharp#456]
I upgraded to the latest version of P# and it seems like Event class does not take the Assert and Assume values as parameters anymore.

Has P# dropped the support for it?

How do I initialize it?

**Comment by pdeligia** [comment]
Hey @ankushdesai, we removed them from the event class in order to optimize for memory in production (as these two are only used during testing). You can now pass these arguments via the machine and runtime `Send` APIs using an optional parameter `SendOptions` (its constructor can set `assert` and `assume`). Btw, please note that `assume` was never really supported by P# (even if you can pass it as a parameter), we left it there for historical reasons (from P) and we might end up either removing it in a future release (have to discuss this with @akashlal). I believe that right now in P# using `assume` gives the same result as using `assert` (instead of e.g. not scheduling paths that would generate more events than the assumption).

**Comment by ankushdesai** [comment]
Thanks, Pantazis. I have updated P to use the latest version of P#.
It would be good if we can figure out the PLogger story.

**Comment by akashlal** [comment]
One of the reasons for this change, in addition to performance optimization, was that we didn't much use of these annotations. If they really are useful, we can consider adding them back in some way, e.g., through annotations on the event class declaration. These annotations would only be interpreted by the testing runtime so there will be no performance implications for production. The current `SendOptions` methodology works as well, but requires one to annotate each `send` to get the same effect as a `P` constraint.

**Comment by pdeligia** [comment]
Hey Ankush, I am finishing up some tasks this week, and then I will try to add support for adding custom logging during testing, so you can then use again the `PLogger`. I don't think it will be too hard to support that.

**Comment by ankushdesai** [comment]
Thanks, please let me know when you are done.

**Comment by pdeligia** [comment]
I just added an issue here #459, so we can track it seperately from this question.
