### ISSUE TITLE
logging Runtime.SendEvent

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#72]
There is a difference in logging when using Machine.Send and RunTime.SendEvent, even when the latter is used to execute on behalf of a machine. This makes it hard to know the origin when using SendEvent.

**Comment by pdeligia** [comment]
Maybe we can use the runtime GetCurrentMachine method to return the id and then pass that along (instead of null).

Some refactoring is required though. Right now the above method asserts that such machine exists (matches the current task id to identify it). Instead, I propose that it simply returns null if a machine cannot be matched, delegating error checking to the caller? Then it should work fine for this issue.

**Comment by akashlal** [comment]
Done like you said. Although I had to change the name of a public API, but I think that is OK.
