### ISSUE TITLE
Replay doesn't work for liveness bugs (when using the lasso detection algorithm)

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#89]
Like the one in ReplicatingStorage.

**Comment by pdeligia** [comment]
Commit 382af1dfd8ab4b0d66c4f1a94b70d284a9f9f141 fixes replay for liveness bugs found with the temperature threshold strategy.

Only state-caching / lasso-detection can now not be reliably replayed. To be more precise, I believe it can be replayed, but it needs some more additional logic to make sure that the assertion is triggered when it should. This is low priority since this technique is still experimental, and not used by users.

**Comment by akashlal** [comment]
Bug only remains for experimental support -- changing label to enhancement.

**Comment by akashlal** [comment]
Assigning this to Rashmi who's taking care of the state caching algorithm,

**Comment by pdeligia** [comment]
My fix in f3dc1083dada08a5dffc82bd95d06f082c62e9ea might be related to this.
