### ISSUE TITLE
asserting that Raise is called from a top-level routine

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#91]
During Bug-finding mode, we should assert that Raise is called only from a top-level routine. I believe this requirement is not checked right now. There must be a way of inspecting the call stack in .NET?

**Comment by pdeligia** [comment]
One way we could do this is by using `Environment.StackTrace` (https://msdn.microsoft.com/en-us/library/system.environment.stacktrace(v=vs.110).aspx). I am not sure how robust this is, since they note "the StackTrace property might not report as many method calls as expected due to code transformations that occur during optimization".

**Comment by akashlal** [comment]
Given that we insist on doing debug build for testing, perhaps this will be ok. Even with optimizations, I don't think we will flag false positives (but may have false negatives).

**Comment by pdeligia** [comment]
Btw, this should also apply to the goto (jump) statement.

**Comment by akashlal** [comment]
I thought that jump gets compiled to raise, so really we just have to do this for raise?

**Comment by akashlal** [comment]
resolved with 2401c4be01fc72d35d123ab90063cb3e67caa371
